version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/dev/rpb/rpb-local-servers/shared/data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=rpb
      - POSTGRES_DB=rpb_db

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rpb
      MONGO_INITDB_ROOT_PASSWORD: S3cret
    ports:
      - "27017:27017"
    volumes:
      - ~/dev/rpb/rpb-local-servers/shared/data/mongo:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: rpb
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://rpb:S3cret@mongodb:27017/
